# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aasist.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'aasist.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61\x61sist.proto\x12\x05\x61udio\"8\n\nAudioChunk\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x16\n\x0eraw_audio_data\x18\x02 \x01(\x0c\"V\n\x0fInferenceResult\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x19\n\x11spoof_probability\x18\x02 \x01(\x02\x12\x14\n\x0cis_authentic\x18\x03 \x01(\x08\x32R\n\x10\x41ntiSpoofService\x12>\n\x0bStreamAudio\x12\x11.audio.AudioChunk\x1a\x16.audio.InferenceResult\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aasist_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOCHUNK']._serialized_start=23
  _globals['_AUDIOCHUNK']._serialized_end=79
  _globals['_INFERENCERESULT']._serialized_start=81
  _globals['_INFERENCERESULT']._serialized_end=167
  _globals['_ANTISPOOFSERVICE']._serialized_start=169
  _globals['_ANTISPOOFSERVICE']._serialized_end=251
# @@protoc_insertion_point(module_scope)
